version: "3"
services:
  monitor-active-server:
    container_name: monitor_active_server
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 8001:8000
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - ./src/config/service.yaml:/app/config/service.yaml
      - /var/run/docker.sock:/var/run/docker.sock
